version: "{build}"

clone_folder: c:\gopath\src\github.com\performancecopilot\speed

environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env

build_script:
  - go test -v ./...
